export const MEAL_CONFIG = {
    noodles: {
        scale: 0.25,
        mass: 3,
        args: [2.2, 0.3, 2.2],
        rotation: [5, 20, 10],
        category: 'carbs',
    },
    bread: {
        scale: 0.25,
        mass: 1,
        args: [2.2, 0.2, 2.2],
        offset: [0, -0.5, 0],
        rotation: [0, 0, 0],
        category: 'carbs',
    },
    salmon: {
        scale: 1,
        mass: 5,
        args: [2, 0.3, 1],
        category: 'protein',
    },
    salad: {
        scale: 25,
        mass: 4,
        args: [3, 0.2, 3],
        category: 'veg',
    },
    vegetable: {
        scale: 10,
        mass: 2,
        args: [1.5, 1, 1.5],
        category: 'veg',
    },
    beef: {
        scale: 0.1,
        mass: 5,
        args: [3, 0.4, 2],
        category: 'protein',
    },
    chicken: {
        scale: 1,
        mass: 5,
        args: [1, 0.8, 3],
        category: 'protein',
    },
    egg: {
        scale: 0.6,
        mass: 3,
        args: [2, 0.5, 3],
        category: 'protein',
    },
    rice: {
        scale: 1,
        mass: 1,
        args: [2, 1.4, 1.3],
        offset: [0, 0.3, 0],
        category: 'carbs',
    },
    potato: {
        scale: 0.2,
        mass: 3,
        args: [3.5, 0.4, 3.5],
        category: 'carbs',
    },
}