export const MEAL_CONFIG = {
    noodles: {
        path: '/models/noodles/scene.gltf',
        scale: 0.25,
        mass: 3,
        args: [2.2, 0.3, 2.2],
        offset: [0, -0.2, 0],
        rotation: [0, 0, 0],
        category: 'carbs',
    },
    bread: {
        path: '/models/bread/scene.gltf',
        scale: 0.25,
        mass: 1,
        args: [2.2, 0.2, 2.2],
        offset: [0, -0.1, 0],
        rotation: [0, 0, 0],
        category: 'carbs',
    },
    salmon: {
        path: '/models/salmon/scene.gltf',
        scale: 1,
        mass: 5,
        args: [2, 0.3, 1],
        offset: [0, -0.15, 0],
        category: 'protein',
    },
    salad: {
        path: '/models/salad/scene.gltf',
        scale: 25,
        mass: 4,
        args: [3, 0.2, 3],
        offset: [0, -0.5, 0],
        category: 'veg',
    },
    vegetable: {
        path: '/models/vegetable/scene.gltf',
        scale: 10,
        mass: 2,
        args: [1.5, 1, 1.5],
        offset: [0, 0, 0],
        category: 'veg',
    },
    beef: {
        path: '/models/beef/scene.gltf',
        scale: 0.1,
        mass: 5,
        args: [3, 0.4, 2],
        offset: [0, -0.4, 0],
        category: 'protein',
    },
    chicken: {
        path: '/models/chicken/scene.gltf',
        scale: 1,
        mass: 5,
        args: [1, 0.8, 3],
        offset: [0, -0.5, 0],
        category: 'protein',
    },
    egg: {
        path: '/models/egg/scene.gltf',
        scale: 1,
        mass: 3,
        args: [2, 0.5, 3],
        offset: [0, -0.2, 0],
        category: 'protein',
    },
    rice: {
        path: '/models/rice/scene.gltf',
        scale: 1,
        mass: 1,
        args: [0.3, 0.1, 0.3],
        offset: [0, -0.1, 0],
        category: 'carbs',
    },
    potato: {
        path: '/models/potato/scene.gltf',
        scale: 0.2,
        mass: 3,
        args: [3.5, 0.4, 3.5],
        offset: [0, -0.2, 0],
        category: 'carbs',
    },
}